//
// DO NOT EDIT THIS FILE!  YOUR CHANGES WILL BE OVERWRITTEN!
//
// This file was machine generated from a system description file
// test.svd.  You can obtain the latest version of svd2go
// and the system description files at github.com/iansmith/svd2go
//
package svd

import "github.com/iansmith/svd/runtime/volatile"

type R1Def volatile.Register32

func (a *R1Def) CastIsSet() bool {
	b := volatile.BitField{Msb: 2, Lsb: 2, Ptr: (*volatile.Register32)(a)}
	return b.HasBits()
}
func (a *R1Def) Concrete() uint32 {
	b := volatile.BitField{Msb: 4, Lsb: 3, Ptr: (*volatile.Register32)(a)}
	return b.Get()
}

type MypDef struct {
	reserved000 volatile.Register32 // 0x0
	reserved001 volatile.Register32 // 0x4
	r1          R1Def               // 0x8
}
